<?php

use Illuminate\Database\Seeder;

class mahasiswaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        for ($i=0; $i < 200 ; $i++) { 
            # code...
        
        DB::table('mahasiswa')->insert([
            // [
            //     'nim' => "1234",
            //     'nama' => "Deki Akbar",
            //     'alamat' => "jln.pemuda",
            //     'jenis_kelamin' => "Laki-Laki",
            //     'no_tlp' => "0899999999",
            //     'email' => "deki".'@gmail.com',
            //     'tempat' => 'sukabumi',
            //     'tanggal' => date('2017-01-12'),
            //     'link' => "1505590327.jpg",
            //     'id_jurusan' => 1,
            // ],
            // [
            //     'nim' => "123",
            //     'nama' => "Diki",
            //     'alamat' => "jln.pemuda",
            //     'jenis_kelamin' => "Laki-Laki",
            //     'no_tlp' => "0899988889",
            //     'email' => "diki".'@gmail.com',
            //     'tempat' => 'sukabumi',
            //     'tanggal' => date('2017-01-12'),
            //     'link' => "1505590327.jpg",
            //     'id_jurusan' => 2,
            // ],
            [
                'nim' => str_random(7),
                'nama' => str_random(7),
                'alamat' => str_random(7),
                'jenis_kelamin' => "Laki-Laki",
                'no_tlp' => str_random(12),
                'email' => str_random(7).'@gmail.com',
                'tempat' => str_random(7),
                'tanggal' => date('2017-01-12'),
                'link' => "1505590327.jpg",
                'id_jurusan' => 1,
            ],
            [
                'nim' => str_random(7),
                'nama' => str_random(7),
                'alamat' => str_random(7),
                'jenis_kelamin' => "Laki-Laki",
                'no_tlp' => str_random(12),
                'email' => str_random(7).'@gmail.com',
                'tempat' => str_random(7),
                'tanggal' => date('2017-01-12'),
                'link' => "1505590327.jpg",
                'id_jurusan' => 1,
            ],
            [
                'nim' => str_random(7),
                'nama' => str_random(7),
                'alamat' => str_random(7),
                'jenis_kelamin' => "Laki-Laki",
                'no_tlp' => str_random(12),
                'email' => str_random(7).'@gmail.com',
                'tempat' => str_random(7),
                'tanggal' => date('2017-01-12'),
                'link' => "1505590327.jpg",
                'id_jurusan' => 1,
            ],
            [
                'nim' => str_random(7),
                'nama' => str_random(7),
                'alamat' => str_random(7),
                'jenis_kelamin' => "Laki-Laki",
                'no_tlp' => str_random(12),
                'email' => str_random(7).'@gmail.com',
                'tempat' => str_random(7),
                'tanggal' => date('2017-01-12'),
                'link' => "1505590327.jpg",
                'id_jurusan' => 1,
            ],
            [
                'nim' => str_random(7),
                'nama' => str_random(7),
                'alamat' => str_random(7),
                'jenis_kelamin' => "Laki-Laki",
                'no_tlp' => str_random(12),
                'email' => str_random(7).'@gmail.com',
                'tempat' => str_random(7),
                'tanggal' => date('2017-01-12'),
                'link' => "1505590327.jpg",
                'id_jurusan' => 1,
            ],
            [
                'nim' => str_random(7),
                'nama' => str_random(7),
                'alamat' => str_random(7),
                'jenis_kelamin' => "Laki-Laki",
                'no_tlp' => str_random(12),
                'email' => str_random(7).'@gmail.com',
                'tempat' => str_random(7),
                'tanggal' => date('2017-01-12'),
                'link' => "1505590327.jpg",
                'id_jurusan' => 1,
            ],
            [
                'nim' => str_random(7),
                'nama' => str_random(7),
                'alamat' => str_random(7),
                'jenis_kelamin' => "Laki-Laki",
                'no_tlp' => str_random(12),
                'email' => str_random(7).'@gmail.com',
                'tempat' => str_random(7),
                'tanggal' => date('2017-01-12'),
                'link' => "1505590327.jpg",
                'id_jurusan' => 1,
            ],
            [
                'nim' => str_random(7),
                'nama' => str_random(7),
                'alamat' => str_random(7),
                'jenis_kelamin' => "Laki-Laki",
                'no_tlp' => str_random(12),
                'email' => str_random(7).'@gmail.com',
                'tempat' => str_random(7),
                'tanggal' => date('2017-01-12'),
                'link' => "1505590327.jpg",
                'id_jurusan' => 1,
            ],
            [
                'nim' => str_random(7),
                'nama' => str_random(7),
                'alamat' => str_random(7),
                'jenis_kelamin' => "Laki-Laki",
                'no_tlp' => str_random(12),
                'email' => str_random(7).'@gmail.com',
                'tempat' => str_random(7),
                'tanggal' => date('2017-01-12'),
                'link' => "1505590327.jpg",
                'id_jurusan' => 1,
            ],
            [
                'nim' => str_random(7),
                'nama' => str_random(7),
                'alamat' => str_random(7),
                'jenis_kelamin' => "Laki-Laki",
                'no_tlp' => str_random(12),
                'email' => str_random(7).'@gmail.com',
                'tempat' => str_random(7),
                'tanggal' => date('2017-01-12'),
                'link' => "1505590327.jpg",
                'id_jurusan' => 1,
            ],
            [
                'nim' => str_random(7),
                'nama' => str_random(7),
                'alamat' => str_random(7),
                'jenis_kelamin' => "Laki-Laki",
                'no_tlp' => str_random(12),
                'email' => str_random(7).'@gmail.com',
                'tempat' => str_random(7),
                'tanggal' => date('2017-01-12'),
                'link' => "1505590327.jpg",
                'id_jurusan' => 1,
            ],
            [
                'nim' => str_random(7),
                'nama' => str_random(7),
                'alamat' => str_random(7),
                'jenis_kelamin' => "Laki-Laki",
                'no_tlp' => str_random(12),
                'email' => str_random(7).'@gmail.com',
                'tempat' => str_random(7),
                'tanggal' => date('2017-01-12'),
                'link' => "1505590327.jpg",
                'id_jurusan' => 1,
            ],
            [
                'nim' => str_random(7),
                'nama' => str_random(7),
                'alamat' => str_random(7),
                'jenis_kelamin' => "Laki-Laki",
                'no_tlp' => str_random(12),
                'email' => str_random(7).'@gmail.com',
                'tempat' => str_random(7),
                'tanggal' => date('2017-01-12'),
                'link' => "1505590327.jpg",
                'id_jurusan' => 1,
            ],
            [
                'nim' => str_random(7),
                'nama' => str_random(7),
                'alamat' => str_random(7),
                'jenis_kelamin' => "Laki-Laki",
                'no_tlp' => str_random(12),
                'email' => str_random(7).'@gmail.com',
                'tempat' => str_random(7),
                'tanggal' => date('2017-01-12'),
                'link' => "1505590327.jpg",
                'id_jurusan' => 1,
            ],
            [
                'nim' => str_random(7),
                'nama' => str_random(7),
                'alamat' => str_random(7),
                'jenis_kelamin' => "Laki-Laki",
                'no_tlp' => str_random(12),
                'email' => str_random(7).'@gmail.com',
                'tempat' => str_random(7),
                'tanggal' => date('2017-01-12'),
                'link' => "1505590327.jpg",
                'id_jurusan' => 1,
            ],
            [
                'nim' => str_random(7),
                'nama' => str_random(7),
                'alamat' => str_random(7),
                'jenis_kelamin' => "Laki-Laki",
                'no_tlp' => str_random(12),
                'email' => str_random(7).'@gmail.com',
                'tempat' => str_random(7),
                'tanggal' => date('2017-01-12'),
                'link' => "1505590327.jpg",
                'id_jurusan' => 1,
            ],
            [
                'nim' => str_random(7),
                'nama' => str_random(7),
                'alamat' => str_random(7),
                'jenis_kelamin' => "Laki-Laki",
                'no_tlp' => str_random(12),
                'email' => str_random(7).'@gmail.com',
                'tempat' => str_random(7),
                'tanggal' => date('2017-01-12'),
                'link' => "1505590327.jpg",
                'id_jurusan' => 1,
            ],
            [
                'nim' => str_random(7),
                'nama' => str_random(7),
                'alamat' => str_random(7),
                'jenis_kelamin' => "Laki-Laki",
                'no_tlp' => str_random(12),
                'email' => str_random(7).'@gmail.com',
                'tempat' => str_random(7),
                'tanggal' => date('2017-01-12'),
                'link' => "1505590327.jpg",
                'id_jurusan' => 1,
            ],
            [
                'nim' => str_random(7),
                'nama' => str_random(7),
                'alamat' => str_random(7),
                'jenis_kelamin' => "Laki-Laki",
                'no_tlp' => str_random(12),
                'email' => str_random(7).'@gmail.com',
                'tempat' => str_random(7),
                'tanggal' => date('2017-01-12'),
                'link' => "1505590327.jpg",
                'id_jurusan' => 1,
            ],

        ]);
        
        }
    }
}
